env:
  - CI=false
  - GENERATE_SOURCEMAP=false
before:
  hooks:
    - go mod tidy
    - sh -c "cd assets && rm -rf build && yarn install --network-timeout 1000000 && export NODE_OPTIONS=--openssl-legacy-provider && yarn run build && cd ../ && zip -r - assets/build >assets.zip"
builds:
  -
    env:
      - CGO_ENABLED=0

    binary: cloudreve

    ldflags:
      - -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=3.8.3.2405' -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.LastCommit={{.ShortCommit}}'

    goos:
      - windows

    goarch:
      - amd64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      cloudreve_{{- .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
    - none*