name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload binary files
        uses: actions/upload-artifact@v3
        with:
          name: cloudreve
          path: dist/Cloudreve_*